---
language: ruby
rvm:
  - 2.4.0
  - 2.3.3
  - 2.2.6
  - 2.1.9
  - 2.0.0
  - 1.9.3
  - 1.8.7
  - ree
  - ruby-head
  - jruby-19mode
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: 1.8.7
    - rvm: ree
gemfile:
  - Gemfile
before_script:
  - bundle exec rake travis:before -t
script: bundle exec rake travis
after_script:
  - bundle exec rake travis:after -t
notifications:
  email:
    recipients:
      - austin@rubyforge.org
    on_success: change
    on_failure: always
sudo: false
